"""fix trgm

Revision ID: 31334f695535
Revises: 46c61e8e717e
Create Date: 2023-01-31 14:17:13.186206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31334f695535'
down_revision = '46c61e8e717e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('birhdate_idx', table_name='client')
    op.create_index('birthdate_idx', 'client', ['birthdate'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('phone_number_idx', 'client', ['phone_number'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('telegram_id_idx', 'client', ['telegram_id'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('telegram_id_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('phone_number_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('birthdate_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('birhdate_idx', 'client', ['birthdate'], unique=False)
    # ### end Alembic commands ###
