"""user_update

Revision ID: 431a3ce7678f
Revises: dd157d36a59e
Create Date: 2023-01-14 23:28:52.813290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431a3ce7678f'
down_revision = 'dd157d36a59e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
