"""nullable_contacts

Revision ID: 46c61e8e717e
Revises: c9bcd1c37a61
Create Date: 2023-01-25 01:39:20.246750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c61e8e717e'
down_revision = 'c9bcd1c37a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
