"""up

Revision ID: ae1787b719bb
Revises: 2c238d2b855a
Create Date: 2023-01-19 00:01:29.940203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1787b719bb'
down_revision = '2c238d2b855a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_idx', table_name='client')
    op.create_index('income_idx', 'client', ['income'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('birthdate_idx', 'user', ['birthdate'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('city_idx', 'user', ['city'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('city_idx', table_name='user', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('birthdate_idx', table_name='user', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('income_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('user_idx', 'client', ['user'], unique=False)
    # ### end Alembic commands ###