"""clients_unique_del

Revision ID: c9bcd1c37a61
Revises: 2ac2e8f08904
Create Date: 2023-01-23 22:09:46.055179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bcd1c37a61'
down_revision = '2ac2e8f08904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_email_key', 'client', type_='unique')
    op.drop_constraint('client_instagram_key', 'client', type_='unique')
    op.drop_constraint('client_linkedin_key', 'client', type_='unique')
    op.drop_constraint('client_phone_number_key', 'client', type_='unique')
    op.drop_constraint('client_telegram_id_key', 'client', type_='unique')
    op.drop_constraint('client_vk_key', 'client', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('client_vk_key', 'client', ['vk'])
    op.create_unique_constraint('client_telegram_id_key', 'client', ['telegram_id'])
    op.create_unique_constraint('client_phone_number_key', 'client', ['phone_number'])
    op.create_unique_constraint('client_linkedin_key', 'client', ['linkedin'])
    op.create_unique_constraint('client_instagram_key', 'client', ['instagram'])
    op.create_unique_constraint('client_email_key', 'client', ['email'])
    # ### end Alembic commands ###
