"""clients

Revision ID: f9a7acad0104
Revises: 8c9d80557e6c
Create Date: 2023-01-19 22:53:19.734405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9a7acad0104'
down_revision = '8c9d80557e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_occupation'), 'occupation', ['occupation'], unique=True)
    op.create_table('client',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user', postgresql.UUID(), nullable=True),
    sa.Column('occupation', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DATE(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('work_place', sa.String(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('imgs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('vk', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['occupation'], ['occupation.occupation'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('instagram'),
    sa.UniqueConstraint('linkedin'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('vk')
    )
    op.create_index('birhdate_idx', 'client', ['birthdate'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('city_idx', 'client', ['city'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('email_idx', 'client', ['email'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('firstname_idx', 'client', ['firstname'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('imgs_idx', 'client', ['imgs'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('income_idx', 'client', ['income'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('instagram_idx', 'client', ['instagram'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('lastname_idx', 'client', ['lastname'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('linkedin_idx', 'client', ['linkedin'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('occupation_idx', 'client', ['occupation'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('vk_idx', 'client', ['vk'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('work_place_idx', 'client', ['work_place'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('work_place_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('vk_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('occupation_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('linkedin_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('lastname_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('instagram_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('income_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('imgs_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('firstname_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('email_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('city_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('birhdate_idx', table_name='client', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('client')
    op.drop_index(op.f('ix_occupation_occupation'), table_name='occupation')
    op.drop_table('occupation')
    # ### end Alembic commands ###
